### PR TITLE
Fix horizontal flip in camera example

### PR DESCRIPTION
**Pull request by caternuson**
Simple fix for #7.

**EDIT** - oops wrong issue number. fixed.

### CODE REVIEW

**Comment by jepler** [comment]
I only wonder if we shouldn't set it in the constructor instead so that it fixes all demos.

**Comment by dhalbert** [comment]
> I only wonder if we shouldn't set it in the constructor instead so that it fixes all demos.

That is a better idea. I assumed that was what this does.

**Review by jepler — APPROVED** [review]
You can merge it this way if you want but as I said in comment form a moment ago I wonder if it wouldn't be better to do it in the camera class so all demos benefit from getting the image orientation right.

**Comment by caternuson** [comment]
Changed fix to be in init instead of user code.

**Review by jepler — APPROVED** [review]
thank you for switching it

**Pull request merged**
