### PR TITLE
Update code.py to handle RTC and NTP

### PR DESCRIPTION
**Pull request by VPTechOps**
Add support to set RTC from NTP with local timezone and DST support

### CODE REVIEW

**Comment by VPTechOps** [comment]
I left the NTP server as us.pool.ntp.org. I didn't know if there was some other suggested value such as: pool.ntp.org, ntp.org,  time.cloudflare.com, time.google.com etc. that we should use

**Comment by dhalbert** [comment]
To fix your formatting problems, see about using `pre-commit`: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code

**Comment by VPTechOps** [comment]
Thanks, Dan, for the pointer to pre-commit. It's going to take some time for me to figure out how to do all of that, since all the instruction seem to be Linux/Unix-based. I'm using a Windows machine and UltraEdit and GitKraken. I'll also have to figure out how to make all the libraries available so I can run pre-commit locally.

**Review by FoamyGuy — APPROVED** [review]
I added one commit to this to make it fallback and continue if the user does not have a WIFI network configured so that this feature is truly optional.

The latest version looks good to me. I tested the updated example successfully on the MEMENTO hardware with 9.0.4.

**Pull request merged**
